# Generated by Django 3.1.2 on 2020-10-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemain', '0002_auto_20201025_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
