# Generated by Django 3.1.2 on 2020-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemain', '0003_auto_20201025_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_different_than_billing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_state',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
