# Generated by Django 3.1.2 on 2020-10-24 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('price_in_base_currency', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_price_in_base_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('on_sale', models.BooleanField(null=True)),
                ('base_currency', models.CharField(choices=[('GBP', '£')], default='GBP', max_length=3)),
                ('options_csv', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('LCH', 'Leads, Collars or Harnesses'), ('CLS', 'Clothes or Shoes'), ('FOT', 'Food and Treats'), ('ACC', 'Accessories'), ('GRO', 'Grooming'), ('CGK', 'Crates, Gates or Kennels'), ('BOO', 'Books - paperback'), ('DIG', 'Digital'), ('OTH', 'Other')], default='OTH', max_length=3, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
